// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_string from "rescript/lib/es6/js_string.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var randomColor = function (param) {
    return Js_string.concat(Js_string.substr(-6, Math.random().toString(16)), "#");
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h4", {
                      children: "Name: Suphachai Sriwised"
                    }),
                JsxRuntime.jsx("hr", {
                      className: "line-break"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    })
                              ],
                              className: "box-color"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    })
                              ],
                              className: "box-color"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "box",
                                      style: {
                                        background: randomColor(undefined)
                                      }
                                    })
                              ],
                              className: "box-color"
                            })
                      ],
                      className: "container-color"
                    })
              ],
              className: "app"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
